### PR TITLE
Added emoji and paginate support :rocket:

### PR DESCRIPTION
**Pull request by varundey**

### CODE REVIEW

**Comment by lukas-h** [comment]
I'm not sure if the sitemap and feed plugin is required, I created a sitemap and both atom and normal rss feed without these plugins

**Comment by varundey** [comment]
Yup you are right. Made a new commit to the file. Do check it :+1:

**Comment by lukas-h** [comment]
You're awesome! ...  
Do the jekyll plugins properly work with gh-pages? Or in general, are plugins supported by gh? I had problems with plugins in the past. :smile:

**Comment by varundey** [comment]
`Kramdown` and `rogue` are the default plugins supported by gh-pages for code highlighting. As for the other plugins go, you have to incorporate them into your site is to generate your site locally and then push your site's static files to your GitHub Pages site. You can read more about it over [here](https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/). Did a lot of research before contributing to your repo :smile:

**Comment by lukas-h** [comment]
hmm so you can't easily for example add a post and then simply push it?

**Comment by varundey** [comment]
oh you can definitely do that. Try building your repo and adding a post with markdown styled code and try to push it. You will see it live on your website

**Pull request merged**
